from io import BytesIO
from datetime import datetime

from fpdf import FPDF


class TermSheetPDF(FPDF):
    def footer(self):
        self.set_y(-8)
        self.set_font("Helvetica", size=7)
        self.set_text_color(110, 120, 120)
        self.cell(0, 4, "For informational purposes only", align="R")


def _write_section_title(pdf, title, x, y, width):
    pdf.set_xy(x, y)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(27, 67, 50)
    pdf.cell(width, 6, title)
    pdf.set_draw_color(82, 183, 136)
    pdf.set_line_width(0.5)
    pdf.line(x, y + 7, x + width, y + 7)


def _write_value(pdf, label, value, x, y, width):
    pdf.set_xy(x, y)
    pdf.set_font("Helvetica", size=8)
    pdf.set_text_color(95, 105, 105)
    pdf.cell(width, 4, label)
    pdf.set_xy(x, y + 4)
    pdf.set_font("Helvetica", "B", size=9)
    pdf.set_text_color(30, 40, 40)
    pdf.cell(width, 5, value)


def _plot_to_buffer(figure):
    image_buffer = BytesIO()
    figure.write_image(file=image_buffer, format="png", width=700, height=420, scale=1)
    image_buffer.seek(0)
    return image_buffer


def generate_term_sheet(inputs, premiums, greeks, call_heatmap_fig, put_heatmap_fig):
    """Return a one-page PDF term sheet for the current option calculation."""
    pdf = TermSheetPDF(orientation="L", unit="mm", format="Letter")
    pdf.set_auto_page_break(auto=False)
    pdf.set_margins(12, 10, 12)
    pdf.add_page()

    page_width = pdf.w - 24
    pdf.set_fill_color(27, 67, 50)
    pdf.rect(0, 0, pdf.w, 27, "F")
    pdf.set_text_color(255, 255, 255)
    pdf.set_xy(12, 7)
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(page_width * 0.62, 8, "Options Pricing Term Sheet")
    pdf.set_xy(12 + page_width * 0.62, 8)
    pdf.set_font("Helvetica", size=8)
    pdf.cell(page_width * 0.38, 5, datetime.now().strftime("%d %b %Y, %H:%M"), align="R")
    pdf.set_xy(12, 18)
    pdf.set_font("Helvetica", size=8)
    pdf.cell(page_width, 4, "Generated by Ketan Duggal | Senior Actuarial Analyst")

    _write_section_title(pdf, "1. Input Parameters", 12, 34, 92)
    input_rows = [
        ("Spot Price", f"INR {inputs['spot_price']:.2f}"),
        ("Strike Price", f"INR {inputs['strike_price']:.2f}"),
        ("Time to Maturity", f"{inputs['time_to_maturity']:.2f} years"),
        ("Volatility", f"{inputs['volatility'] * 100:.2f}%"),
        ("Risk-Free Rate", f"{inputs['risk_free_rate'] * 100:.2f}%"),
        ("Dividend Yield", f"{inputs['dividend_yield'] * 100:.2f}%"),
    ]
    for index, (label, value) in enumerate(input_rows):
        x = 12 + (index % 2) * 48
        y = 45 + (index // 2) * 14
        _write_value(pdf, label, value, x, y, 44)

    _write_section_title(pdf, "2. Pricing & Risk (Greeks)", 115, 34, 148)
    headers = [("", 30), ("Call", 38), ("Put", 38)]
    x = 115
    pdf.set_fill_color(232, 245, 240)
    pdf.set_text_color(27, 67, 50)
    pdf.set_font("Helvetica", "B", 8)
    for header, width in headers:
        pdf.set_xy(x, 45)
        pdf.cell(width, 7, header, fill=True, align="C")
        x += width
    pricing_rows = [
        ("Premium", premiums["call"], premiums["put"], "INR {:.4f}"),
        ("Delta", greeks["delta_call"], greeks["delta_put"], "{:.4f}"),
        ("Gamma", greeks["gamma"], greeks["gamma"], "{:.4f}"),
        ("Theta", greeks["theta_call"], greeks["theta_put"], "{:.4f}"),
        ("Vega", greeks["vega"], greeks["vega"], "{:.4f}"),
    ]
    for row_index, (label, call_value, put_value, formatter) in enumerate(pricing_rows):
        y = 52 + row_index * 7
        pdf.set_fill_color(248, 250, 249) if row_index % 2 == 0 else pdf.set_fill_color(255, 255, 255)
        pdf.set_text_color(40, 50, 50)
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_xy(115, y)
        pdf.cell(30, 7, label, fill=True)
        pdf.set_font("Helvetica", size=8)
        pdf.set_xy(145, y)
        pdf.cell(38, 7, formatter.format(call_value), fill=True, align="C")
        pdf.set_xy(183, y)
        pdf.cell(38, 7, formatter.format(put_value), fill=True, align="C")

    _write_section_title(pdf, "3. Sensitivity Analysis", 12, 91, page_width)
    call_image = _plot_to_buffer(call_heatmap_fig)
    put_image = _plot_to_buffer(put_heatmap_fig)
    image_y = 101
    image_width = 130
    image_height = 78
    pdf.image(call_image, x=12, y=image_y, w=image_width, h=image_height)
    pdf.image(put_image, x=148, y=image_y, w=image_width, h=image_height)

    output = pdf.output()
    pdf_buffer = BytesIO(output)
    pdf_buffer.seek(0)
    return pdf_buffer
